import Header from '@/components/Header'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Button, Container } from 'reactstrap'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main >
        <Container className="py-5 my-5 text-center">
          <h1 className="mt-5 display-1">
            O melhor jeito de comprar o que você ama
          </h1>
          <p className="my-4">
            Bem-vindo à nossa loja, o destino perfeito para os apaixonados por produtos Apple. Aqui, oferecemos o mais alto padrão em qualidade, inovação e design que você espera da marca. Descubra uma experiência de compra única, onde cada produto é cuidadosamente selecionado para atender às suas necessidades e desejos. De iPhones poderosos a MacBooks incrivelmente elegantes, proporcionamos o acesso direto aos dispositivos que enriquecem sua vida digital. Explore nossa coleção e experimente o prazer de ter o melhor ao alcance das suas mãos.
          </p>
          <Link href="/products">
            <Button color="dark" className="px-4 pb-2">
              Conheça nossos produtos!
            </Button>
          </Link>
        </Container>
      </main>
    </>
  )
}

export default Home